version: '3.4'

services:
  vue-vben-client:
    build:
      context: .
    restart: always
    ports:
      - "40080:80"
    networks:
      - framework

networks:
  framework:
    external:
      name: ly_app_net
